---
title: "7 Dispersal"
format: gfm
editor: source
editor_options: 
  chunk_output_type: inline
execute:
  freeze: auto
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, error = FALSE)
```

```{r}
library(tidyverse)
library(sf)
#library(ozmaps)
source("constants.R")
library(ggrepel)

source("constants.R")

options(readr.show_col_types = FALSE)
```

```{r}
kml_files <- list.files("dispersal",".kml",full.names = TRUE)

disp_data <- map(kml_files,st_read) %>% bind_rows()

ab <- st_read("dispersal/Arthur_Bay.kml")
```

```{r}
gbr_coast <- st_read("maps/GBR_NESP-TWQ-5/BaseLayers/",layer = "GBR_coastlineONLY")
gbr_tc <- st_read("maps/GBR_NESP-TWQ-5/BaseLayers/",layer = "GBR_towncities")
gbr_features <- st_read("maps/GBR_NESP-TWQ-5/BaseLayers/",layer = "TS_AIMS_NESP_Torres_Strait_Features_V1b_with_GBR_Features")

sf_use_s2(FALSE) # the input geometries are bad, and wrong spherically
x1 <- st_make_valid(gbr_features)

xmn=146.0
ymn=-19.3
xmx=146.9
ymx=-18.35

gbr_ft_cropped <- st_crop(x1, xmin = xmn, ymin = ymn, xmax = xmx, ymax = ymx) #%>% filter(LEVEL_1=="Island")
gbr_coast_cropped <- st_crop(gbr_coast,xmin = xmn, ymin = ymn, xmax = xmx, ymax = ymx)

projcrs <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"

#sites_sf <- st_as_sf(sites_data,coords = c("lon", "lat"),crs = projcrs)

#sf_oz <- ozmap("states")
```

```{r}
ggplot() + 
  geom_sf(data = gbr_ft_cropped %>% filter(LEVEL_1=="Island")) +
  geom_sf(data = gbr_coast_cropped) +
  geom_sf(data = ab) +
  xlab("") + ylab("")
```
